### ISSUE TITLE
Unable to fetch or create tickets using Rest API.

### ISSUE THREAD

**Issue by wkm97** [uvdesk/api-bundle#2]
I created a token for the authentication in uvdesk.
![image](https://user-images.githubusercontent.com/31875755/72858961-534a6b80-3cfd-11ea-9f67-4af97f624239.png)

and I'm unable to fetch tickets using it. There is an internal server error found when trying to fetch tickets.
![image](https://user-images.githubusercontent.com/31875755/72859032-81c84680-3cfd-11ea-83fb-c8092f85b87d.png)

May I know what did I miss or is there any log file to trace the problem?

**Comment by papnoisanjeev** [comment]
@wkm97

Write **Basic** instead of **Bearer** for Authorization.
and secondly locate this file.
**config->packages->security.yaml**  and open security.yaml.

Now you just need to change the sequence in **firewalls** made change as per given in screenshot.
check screen shot.


![api](https://user-images.githubusercontent.com/42460055/72869234-9101c100-3d0a-11ea-9dd9-28b7b0cf475b.png)

Clear your project cache by:
**php bin/console c:c**

**Comment by wkm97** [comment]
Thanks for replying. I had followed the steps that you kindly provide me and cleared the cache. It successfully returned something to me but there are still problem occurred.
![image](https://user-images.githubusercontent.com/31875755/72871289-5b1e0600-3d25-11ea-8490-aa8f3ab9cf37.png)
The log file is shown as follows:
![image](https://user-images.githubusercontent.com/31875755/72871315-738e2080-3d25-11ea-8c6c-5d2e53054b21.png)

**Comment by papnoisanjeev** [comment]
@wkm97 

You are getting **internal server error**  may be it can be due to syntax error or due to some exception while doing API request.

Locate file.
**vendor->uvdesk->api-bundle->Security->Guards->APIGuard.php** 

Open file and find **getCredentials()** function  and dump step by step
like  **dump($authorization_key); die;**
and find from where you are getting exception.


We have checked an working fine for us.

![APITickets](https://user-images.githubusercontent.com/42460055/72876143-db3f6e00-3d1b-11ea-8966-e30e188dd5cd.png)

**Comment by wkm97** [comment]
I added the dump function over here:
![image](https://user-images.githubusercontent.com/31875755/72883591-8b729e00-3d3f-11ea-92fb-380a164ff709.png)

Where can I find the dumped value?
Is it correct that I start this dump server and it will display it over here? It didn't show anything when I try to fetch the tickets.
![image](https://user-images.githubusercontent.com/31875755/72883763-db516500-3d3f-11ea-9d64-17f7fac2e73d.png)

**Comment by papnoisanjeev** [comment]
@wkm97 
You will see values of variable which you have dump in response of your API request.
All the API request will go through this API guard first so you can check it here where you are failing to make a API request.

![APIDump1](https://user-images.githubusercontent.com/42460055/72884984-0c746a00-3d2d-11ea-8219-b17ff8236a26.png)

**Comment by papnoisanjeev** [comment]
@wkm97
Is your issue resolved?

If not, you can create a support ticket by mail : **support@uvdesk.com** here or from visiting here
https://support.uvdesk.com/en/customer/create-ticket/

**Comment by wkm97** [comment]
There are other issues on my side (not about uvdesk), I will continue trying. If problem encountered I will create a support ticket.

**Comment by papnoisanjeev** [comment]
@wkm97  
Sure you can create a support ticket if you are facing any problem with 
uvdesk (https://github.com/uvdesk/community-skeleton).

**Comment by papnoisanjeev** [comment]
@wkm97 
open your project go to:       **public->.htaccess**
add these lines in your .htaccess file:

    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

![htaccess](https://user-images.githubusercontent.com/42460055/73533490-f9f0e380-4444-11ea-85f6-4c7f90df383b.png)



And clear your project cache by:
**php bin/console c:c** 

and try using this if it works for you.

**Comment by tigersf2** [comment]
@papnoisanjeev i have the same error, have u a solution to resolve it ?
i tried to get tickets list using curl :

`curl -X GET -H "Authorization: Bearer ZJ0B7DYXGDP6EJPLFQD3SZRXEXVOODNJ6F36IIMGMCAK8SQRE8ZFMPSCJKFNJBVD" "https://neovare.org/api/v1/tickets"
`

**Comment by tigersf2** [comment]
.htaccess is correct, it's like mentionned here 

in log file, i found this error : 

![Capture du 2020-03-17 23-22-12](https://user-images.githubusercontent.com/15524902/76907443-8432c100-68a6-11ea-9c42-7c40429e5904.png)

**Comment by tigersf2** [comment]
@wkm97 are you succeed to resolve the issue ?

**Comment by tigersf2** [comment]
it resolved, i just replace **Bearer** by **Basic**

`curl -X GET -H "Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" "https://xxxxxxxxxxx/api/v1/tickets" `

**Comment by papnoisanjeev** [comment]
@tigersf2 
Glad to know that your issue has been resolved.
For more details check this blog: 
https://www.uvdesk.com/en/blog/api-resource/

**Comment by steven4547466** [comment]
I know I'm reopening an old ticket, but I am getting this same error with, but only when attempting to POST to `/tickets` the weirdest thing was, I used to be able to I successfully created 4 tickets before I started getting the 500 error. I can also still GET /tickets and return all ticket data successfully, but posting just stopped working for whatever reason.
